name: CI Workflow

on: push

jobs:
  static_validation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.1.1

      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.4
        with:
          node-version: 14.17.0

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Check Format
        run: npm run check:format

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Typecheck
        run: npm run typecheck
